### PR TITLE
FATIP-X-Governance

### PR DESCRIPTION
**Pull request by JFletcherTaylor**
Description of FATIP Editors semi-weekly meeting structure.

### CODE REVIEW

**Comment by drkatz** [comment]
@AdamSLevy Would appreciate your review and ratification :smile:

**Comment by PaulBernier** [comment]
Actually what do you think about fixing the date/time at least 48h in advance? 24h is quite a short notice when we have people all around the globe.

**Comment by JFletcherTaylor** [comment]
All for that ya.

**Comment by drkatz** [comment]
This all looks good to me guys :+1: Shall we merge?

**Comment by AdamSLevy** [comment]
It looks pretty good but I was wondering what it would look like if there were things learned during implementation that should influence the spec after it has been Accepted but before making it to Final? Should we add some language to address this?

**Comment by drkatz** [comment]
I think that would be appropriate. As long as the "spirit" of the standard is not significantly changed by those lessons learned that's all good.

Nothing stops motivated standard creators from beginning implementation before acceptance in order to  learn those lessons :wink:

**Pull request merged**
